
service: todolist
frameworkVersion: '3'
useDotenv: true
provider:
  name: google
  runtime: nodejs20
  region: us-central1
  project: ${env:GCP_PROJECT_ID}
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY}
    
plugins:
  - serverless-google-cloudfunctions

functions:
  createTask:
    handler: handler
    events:
      - http: tasks/save

  listTasks:
    handler: handler
    events:
      - http: tasks/list

  getTask:
    handler: handler
    events:
      - http: tasks/get

  updateTask:
    handler: handler
    events:
      - http: tasks/put/{id}

  deleteTask:
    handler: handler
    events:
      - http: tasks/delete/{id}