service: todolist
frameworkVersion: '3'
useDotenv: true
custom:
  dotenv:
    path: .env
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  httpApi:
    cors:
      allowedOrigins:
      - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - Token
      allowCredentials: false
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

plugins:
      - serverless-dotenv-plugin
      - serverless-offline

functions:
  createTask:
    handler: index.handler
    events:
      - http:
          path: tasks/save
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - Token
          integration: lambda-proxy
          
  listTasks:
    handler: index.handler
    events:
      - http:
          path: tasks/list
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - Token
          integration: lambda-proxy
          
  getTask:
    handler: index.handler
    events:
      - http:
          path: tasks/get/{id}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - Token
          integration: lambda-proxy
          
  updateTask:
    handler: index.handler
    events:
      - http:
          path: tasks/put/{id}
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - Token
          integration: lambda-proxy
          
  deleteTask:
    handler: index.handler
    events:
      - http:
          path: tasks/delete/{id}
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - Token
          integration: lambda-proxy
          
# Resources: DynamoDB table, S3 bucket and CloudFront
resources:
  Resources:
    SpaBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-spa-bucket-${aws:accountId}
        AccessControl: Private
        WebsiteConfiguration:
          IndexDocument: index.html
        CorsConfiguration:
          CorsRules:
            - AllowedMethods: ["GET", "HEAD"]
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              MaxAge: 3600

    SpaBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref SpaBucket
        PolicyDocument:
          Statement:
            - Sid: AllowCloudFrontGetObject
              Effect: Allow
              Principal:
                CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
              Action: "s3:GetObject"
              Resource: !Sub "${SpaBucket.Arn}/*"

    CloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: "OAI for SPA bucket"

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          DefaultRootObject: index.html
          Origins:
            - Id: S3SpaOrigin
              DomainName: !GetAtt SpaBucket.RegionalDomainName
              S3OriginConfig:
                OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
          DefaultCacheBehavior:
            TargetOriginId: S3SpaOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - OPTIONS
              - GET
              - HEAD
            CachedMethods:
              - OPTIONS
              - GET
              - HEAD
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
              Headers:
                - Origin  # important to forward so preflight/origin checks can work when necessary
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
            MinTTL: 0
            DefaultTTL: 3600
            MaxTTL: 31536000
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
          CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0

  Outputs:
    CloudFrontUrl:
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - !GetAtt CloudFrontDistribution.DomainName
      Export:
        Name: CloudFrontUrl
    ApiUrl:
      Description: "API endpoint (REST API)"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - Ref: "AWS::Region"
            - ".amazonaws.com/"
            - ${self:provider.stage}
    SpaBucketName:
      Value: !Ref SpaBucket
    CloudFrontDomain:
      Value: !GetAtt CloudFrontDistribution.DomainName
    CloudFrontDistributionId:
      Value: !Ref CloudFrontDistribution
  
