swagger: "2.0"

info:
  title: todolist-api
  version: "1.0.0"

schemes:
  - https

paths:
  /tasks/{proxy+}:
    x-google-backend:
      address: ${cloud_function_url}
      path_translation: APPEND_PATH_TO_ADDRESS

    options:
      operationId: optionsTasks
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        "204":
          description: CORS preflight

    get:
      operationId: getTasksProxy
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK

    post:
      operationId: postTasksProxy
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK

    put:
      operationId: putTasksProxy
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK

    delete:
      operationId: deleteTasksProxy
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK