swagger: "2.0"

info:
  title: todolist-api
  version: "1.0.0"

schemes:
  - https

produces:
  - application/json

x-google-backend:
  address: ${cloud_function_url}
  path_translation: APPEND_PATH_TO_ADDRESS
  disable_auth: true

paths:
  /tasks/save:
    options:
      operationId: optionsTasksSave
      responses:
        "204":
          description: CORS preflight

    post:
      operationId: postTasksSave
      responses:
        "200":
          description: OK

  /tasks/list:
    options:
      operationId: optionsTasksList
      responses:
        "204":
          description: CORS preflight

    get:
      operationId: getTasksList
      responses:
        "200":
          description: OK

  /tasks/get/{id}:
    options:
      operationId: optionsTasksGet
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "204":
          description: CORS preflight

    get:
      operationId: getTaskById
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK

  /tasks/put/{id}:
    options:
      operationId: optionsTasksPut
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "204":
          description: CORS preflight

    put:
      operationId: putTaskById
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK

  /tasks/delete/{id}:
    options:
      operationId: optionsTasksDelete
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "204":
          description: CORS preflight

    delete:
      operationId: deleteTaskById
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK